In [1]:
# Task 1 - Data Cleaning and Preprocessing

In [31]:
# Customers Dataset

In [2]:
import pandas as pd

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [5]:
df = pd.read_csv("customers-100.csv")

In [6]:
display(df.head())

   Index      Customer Id First Name Last Name                          Company               City                     Country                 Phone 1                Phone 2                        Email Subscription Date                      Website
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter                  Rasmussen Group       East Leonard                       Chile            229.077.5154       397.884.0519x718     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1      2  1Ef7b82A4CAAD10    Preston    Lozano                      Vega-Gentry  East Jimmychester                    Djibouti              5153435776       686-620-1820x944              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2      3  6F94879bDAfE5a6        Roy     Berry                    Murillo-Perry      Isabelborough         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3      4  5Cef8BFA16c5e3c      Linda     Olsen  Dominguez, Mcmillan and Donovan         Bensonview          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      5  053d585Ab6b3159     Joanna    Bender         Martin, Lang and Andrade     West Priscilla  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB
None

In [8]:
print(df.shape)

(100, 12)

In [9]:
print(df.duplicated().sum())

0

In [11]:
df = df.rename(columns={"Customer Id": "Customer_ID",
                       "First Name": "First_Name",
                       "Last Name": "Last_Name",
                       "Phone 1": "Phone_1",
                       "Phone 2": "Phone_2",
                       "Subscription Date": "Subscription_Date"})

In [12]:
print(df.columns)

Index(['Index', 'Customer_ID', 'First_Name', 'Last_Name', 'Company', 'City', 'Country', 'Phone_1', 'Phone_2', 'Email', 'Subscription_Date', 'Website'], dtype='object')

In [13]:
print(df.isna().sum())

Index                0
Customer_ID          0
First_Name           0
Last_Name            0
Company              0
City                 0
Country              0
Phone_1              0
Phone_2              0
Email                0
Subscription_Date    0
Website              0
dtype: int64

In [14]:
df["City"] = df["City"].fillna("Unknown")

In [15]:
df["Country"] = df["Country"].fillna("Unknown")

In [16]:
df["Company"] = df["Company"].fillna("Not Available")

In [17]:
df["Subscription_Date"] = pd.to_datetime(
    df["Subscription_Date"],
    errors="coerce"
)

In [18]:
print(df.dtypes)

Index                         int64
Customer_ID                  object
First_Name                   object
Last_Name                    object
Company                      object
City                         object
Country                      object
Phone_1                      object
Phone_2                      object
Email                        object
Subscription_Date    datetime64[ns]
Website                      object
dtype: object

In [19]:
df["First_Name"] = df["First_Name"].str.lower().str.strip()

In [20]:
df["Last_Name"] = df["Last_Name"].str.lower().str.strip()

In [21]:
df["Country"] = df["Country"].str.title().str.strip()

In [22]:
df["City"] = df["City"].str.title().str.strip()

In [23]:
display(df.head())

   Index      Customer_ID First_Name Last_Name                          Company               City                     Country                 Phone_1                Phone_2                        Email Subscription_Date                      Website
0      1  DD37Cf93aecA6Dc     sheryl    baxter                  Rasmussen Group       East Leonard                       Chile            229.077.5154       397.884.0519x718     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1      2  1Ef7b82A4CAAD10    preston    lozano                      Vega-Gentry  East Jimmychester                    Djibouti              5153435776       686-620-1820x944              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2      3  6F94879bDAfE5a6        roy     berry                    Murillo-Perry      Isabelborough         Antigua And Barbuda         +1-539-402-0259    (496)978-3969x58947          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3      4  5Cef8BFA16c5e3c      linda     olsen  Dominguez, Mcmillan and Donovan         Bensonview          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      5  053d585Ab6b3159     joanna    bender         Martin, Lang and Andrade     West Priscilla  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/

In [24]:
assert df.duplicated().sum() == 0

In [25]:
print("Validation Successful!")

Validation Successful!

In [26]:
df.to_csv("cleaned_customers_dataset.csv", index=False)

In [27]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [28]:
cleaned_df = pd.read_csv("cleaned_customers_dataset.csv")

In [29]:
display(cleaned_df)

    Index      Customer_ID First_Name Last_Name                          Company               City                     Country                 Phone_1                 Phone_2                           Email Subscription_Date                            Website
0       1  DD37Cf93aecA6Dc     sheryl    baxter                  Rasmussen Group       East Leonard                       Chile            229.077.5154        397.884.0519x718        zunigavanessa@smith.info        2020-08-24         http://www.stephenson.com/
1       2  1Ef7b82A4CAAD10    preston    lozano                      Vega-Gentry  East Jimmychester                    Djibouti              5153435776        686-620-1820x944                 vmata@colon.com        2021-04-23              http://www.hobbs.com/
2       3  6F94879bDAfE5a6        roy     berry                    Murillo-Perry      Isabelborough         Antigua And Barbuda         +1-539-402-0259     (496)978-3969x58947             beckycarr@hogan.com        2020-03-25           http://www.lawrence.com/
3       4  5Cef8BFA16c5e3c      linda     olsen  Dominguez, Mcmillan and Donovan         Bensonview          Dominican Republic  001-808-617-6467x12895         +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02         http://www.good-lyons.com/
4       5  053d585Ab6b3159     joanna    bender         Martin, Lang and Andrade     West Priscilla  Slovakia (Slovak Republic)  001-234-203-0635x76146   001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17        https://goodwin-ingram.com/
..    ...              ...        ...       ...                              ...                ...                         ...                     ...                     ...                             ...               ...                                ...
95     96  cb8E23e48d22Eae       karl     greer                        Carey LLC       East Richard                      Guyana     (188)169-1674x58692    001-841-293-3519x614                hhart@jensen.com        2022-01-30            http://hayes-perez.com/
96     97  CeD220bdAaCfaDf       lynn  atkinson            Ware, Burns and Oneal       New Bradview                   Sri Lanka         +1-846-706-2218            605.413.3198               vkemp@ferrell.com        2021-07-10         https://novak-allison.com/
97     98  28CDbC0dFe4b1Db       fred    guerra                    Schmitt-Jones         Ortegaland             Solomon Islands    +1-753-067-8419x7170   +1-632-666-7507x92121                swagner@kane.org        2021-09-18              https://www.ross.com/
98     99  c23d1D9EE8DEB0A     yvonne    farmer               Fitzgerald-Harrell    Lake Elijahview                       Aruba           (530)311-9786  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11               http://watkins.info/
99    100  2354a0E336A91A1   clarence    haynes               Le, Nash and Cross          Judymouth                    Honduras           (753)813-6941            783.639.1472          colleen91@faulkner.biz        2020-03-11  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

In [30]:
# People Dataset

In [32]:
people_df = pd.read_csv("people-100.csv")

In [33]:
display(people_df.head())

   Index          User Id First Name Last Name     Sex                       Email                   Phone Date of birth           Job Title
0      1  88F7B33d2bcf9f5     Shelby   Terrell    Male        elijah57@example.net  001-084-906-7849x73518    1945-10-26     Games developer
1      2  f90cD3E76f1A9b9    Phillip   Summers  Female       bethany14@example.com       214.112.6044x4913    1910-03-24      Phytotherapist
2      3  DbeAb8CcdfeFC2c   Kristine    Travis    Male       bthompson@example.com            277.609.7938    1992-07-02           Homeopath
3      4  A31Bee3c201ef58    Yesenia  Martinez    Male   kaitlinkaiser@example.com            584.094.6111    2017-08-03   Market researcher
4      5  1bA7A3dc874da3c       Lori      Todd    Male  buchananmanuel@example.net       689-207-3558x7233    1938-12-01  Veterinary surgeon

In [34]:
print(people_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    int64
 1   User Id        100 non-null    object
 2   First Name     100 non-null    object
 3   Last Name      100 non-null    object
 4   Sex            100 non-null    object
 5   Email          100 non-null    object
 6   Phone          100 non-null    object
 7   Date of birth  100 non-null    object
 8   Job Title      100 non-null    object
dtypes: int64(1), object(8)
memory usage: 7.2+ KB
None

In [35]:
print(people_df.shape)

(100, 9)

In [36]:
print(people_df.duplicated().sum())

0

In [37]:
people_df = people_df.drop_duplicates()

In [38]:
print(people_df.duplicated().sum())

0

In [39]:
people_df = people_df.rename(columns={
    "First Name": "First_Name",
    "Last Name": "Last_Name",
    "Job Title": "Job_Title",
    "Date of Birth": "Date_of_Birth",
    "Phone": "Phone_Number"
})

In [40]:
print(people_df.columns)

Index(['Index', 'User Id', 'First_Name', 'Last_Name', 'Sex', 'Email', 'Phone_Number', 'Date of birth', 'Job_Title'], dtype='object')

In [41]:
print(people_df.isna().sum())

Index            0
User Id          0
First_Name       0
Last_Name        0
Sex              0
Email            0
Phone_Number     0
Date of birth    0
Job_Title        0
dtype: int64

In [42]:
people_df["First_Name"] = people_df["First_Name"].fillna("unknown")

In [43]:
people_df["Last_Name"] = people_df["Last_Name"].fillna("unknown")

In [44]:
people_df["Job_Title"] = people_df["Job_Title"].fillna("Not Available")

In [45]:
people_df["Sex"] = people_df["Sex"].fillna("Unknown")

In [46]:
people_df["Phone_Number"] = (
    people_df["Phone_Number"]
    .astype(str)
    .str.replace(r'[^0-9]', '', regex=True)
)

In [52]:
people_df["Date of birth"] = pd.to_datetime(
    people_df["Date of birth"],
    errors="coerce"
)

In [53]:
people_df = people_df.rename(columns={
    "First Name": "First_Name",
    "Last Name": "Last_Name",
    "Job Title": "Job_Title",
    "Date of birth": "Date_of_Birth",
    "Phone": "Phone_Number"
})

In [54]:
people_df["Date_of_Birth"] = pd.to_datetime(
    people_df["Date_of_Birth"],
    errors="coerce"
)

In [55]:
people_df = people_df.rename(columns={
    "First Name": "First_Name",
    "Last Name": "Last_Name",
    "Job Title": "Job_Title",
    "Date of birth": "Date_of_Birth",
    "Phone": "Phone_Number"
})

In [56]:
display(people_df.head())

print(people_df.dtypes)

assert people_df.duplicated().sum() == 0

print("Validation Successful!")

people_df.to_csv("cleaned_people_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

   Index          User Id First_Name Last_Name     Sex                       Email        Phone_Number Date_of_Birth           Job_Title
0      1  88F7B33d2bcf9f5     Shelby   Terrell    Male        elijah57@example.net  001084906784973518    1945-10-26     Games developer
1      2  f90cD3E76f1A9b9    Phillip   Summers  Female       bethany14@example.com      21411260444913    1910-03-24      Phytotherapist
2      3  DbeAb8CcdfeFC2c   Kristine    Travis    Male       bthompson@example.com          2776097938    1992-07-02           Homeopath
3      4  A31Bee3c201ef58    Yesenia  Martinez    Male   kaitlinkaiser@example.com          5840946111    2017-08-03   Market researcher
4      5  1bA7A3dc874da3c       Lori      Todd    Male  buchananmanuel@example.net      68920735587233    1938-12-01  Veterinary surgeon

Index                     int64
User Id                  object
First_Name               object
Last_Name                object
Sex                      object
Email                    object
Phone_Number             object
Date_of_Birth    datetime64[ns]
Job_Title                object
dtype: object
Validation Successful!
Cleaned dataset saved successfully!

In [57]:
cleaned_people_df = pd.read_csv("cleaned_people_dataset.csv")

display(cleaned_people_df.head())

   Index          User Id First_Name Last_Name     Sex                       Email      Phone_Number Date_of_Birth           Job_Title
0      1  88F7B33d2bcf9f5     Shelby   Terrell    Male        elijah57@example.net  1084906784973518    1945-10-26     Games developer
1      2  f90cD3E76f1A9b9    Phillip   Summers  Female       bethany14@example.com    21411260444913    1910-03-24      Phytotherapist
2      3  DbeAb8CcdfeFC2c   Kristine    Travis    Male       bthompson@example.com        2776097938    1992-07-02           Homeopath
3      4  A31Bee3c201ef58    Yesenia  Martinez    Male   kaitlinkaiser@example.com        5840946111    2017-08-03   Market researcher
4      5  1bA7A3dc874da3c       Lori      Todd    Male  buchananmanuel@example.net    68920735587233    1938-12-01  Veterinary surgeon

In [58]:
# Organizations Dataset

In [59]:
org_df = pd.read_csv("organizations-100.csv")

In [60]:
display(org_df.head())

   Index  Organization Id                     Name                         Website           Country                                     Description  Founded                     Industry  Number of employees
0      1  FAB0d41d5b5d22c              Ferrell LLC              https://price.net/  Papua New Guinea             Horizontal empowering knowledgebase     1990                     Plastics                 3498
1      2  6A7EdDEA9FaDC52  Mckinney, Riley and Day  http://www.hall-buchanan.info/           Finland             User-centric system-worthy leverage     2015  Glass / Ceramics / Concrete                 4952
2      3  0bFED1ADAE4bcC1               Hester Ltd       http://sullivan-reed.com/             China                  Switchable scalable moratorium     1971                Public Safety                 5287
3      4  2bFC1Be8a4ce42f           Holder-Sellers             https://becker.com/      Turkmenistan  De-engineered systemic artificial intelligence     2004                   Automotive                  921
4      5  9eE8A6a4Eb96C24              Mayer Group          http://www.brewer.com/         Mauritius              Synchronized needs-based challenge     1991               Transportation                 7870

In [61]:
print(org_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Index                100 non-null    int64
 1   Organization Id      100 non-null    object
 2   Name                 100 non-null    object
 3   Website              100 non-null    object
 4   Country              100 non-null    object
 5   Description          100 non-null    object
 6   Founded              100 non-null    int64
 7   Industry             100 non-null    object
 8   Number of employees  100 non-null    int64
dtypes: int64(3), object(6)
memory usage: 7.2+ KB
None

In [62]:
print(org_df.shape)

(100, 9)

In [63]:
print(org_df.duplicated().sum())

0

In [64]:
org_df = org_df.drop_duplicates()

In [65]:
print(org_df.duplicated().sum())

0

In [66]:
org_df = org_df.rename(columns={
    "Organization Id": "Organization_ID",
    "Industry": "Industry_Category",
    "Number of employees": "Employee_Count",
    "Website": "Website_URL"
})

In [67]:
print(org_df.columns)

Index(['Index', 'Organization_ID', 'Name', 'Website_URL', 'Country', 'Description', 'Founded', 'Industry_Category', 'Employee_Count'], dtype='object')

In [68]:
print(org_df.isna().sum())

Index                0
Organization_ID      0
Name                 0
Website_URL          0
Country              0
Description          0
Founded              0
Industry_Category    0
Employee_Count       0
dtype: int64

In [69]:
org_df["Industry_Category"] = (
    org_df["Industry_Category"]
    .fillna("Unknown")
)

In [70]:
org_df["Employee_Count"] = (
    org_df["Employee_Count"]
    .fillna(org_df["Employee_Count"].median())
)

In [71]:
org_df["Website_URL"] = (
    org_df["Website_URL"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [72]:
org_df["Industry_Category"] = (
    org_df["Industry_Category"]
    .str.title()
    .str.strip()
)

In [73]:
org_df["Employee_Count"] = pd.to_numeric(
    org_df["Employee_Count"],
    errors="coerce"
)

In [74]:
display(org_df.head())

   Index  Organization_ID                     Name                     Website_URL           Country                                     Description  Founded            Industry_Category  Employee_Count
0      1  FAB0d41d5b5d22c              Ferrell LLC              https://price.net/  Papua New Guinea             Horizontal empowering knowledgebase     1990                     Plastics            3498
1      2  6A7EdDEA9FaDC52  Mckinney, Riley and Day  http://www.hall-buchanan.info/           Finland             User-centric system-worthy leverage     2015  Glass / Ceramics / Concrete            4952
2      3  0bFED1ADAE4bcC1               Hester Ltd       http://sullivan-reed.com/             China                  Switchable scalable moratorium     1971                Public Safety            5287
3      4  2bFC1Be8a4ce42f           Holder-Sellers             https://becker.com/      Turkmenistan  De-engineered systemic artificial intelligence     2004                   Automotive             921
4      5  9eE8A6a4Eb96C24              Mayer Group          http://www.brewer.com/         Mauritius              Synchronized needs-based challenge     1991               Transportation            7870

In [75]:
print(org_df.dtypes)

Index                 int64
Organization_ID      object
Name                 object
Website_URL          object
Country              object
Description          object
Founded               int64
Industry_Category    object
Employee_Count        int64
dtype: object

In [76]:
assert org_df.duplicated().sum() == 0

In [77]:
print("Validation Successful!")

Validation Successful!

In [78]:
org_df.to_csv("cleaned_organizations_dataset.csv", index=False)

In [79]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [80]:
# Retail Sales Data

In [81]:
sales_df = pd.read_csv("train.csv")

In [82]:
display(sales_df.head())

   PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
4            5         0       3                           Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S

In [83]:
print(sales_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [84]:
print(sales_df.shape)

(891, 12)

In [85]:
print(sales_df.duplicated().sum())

0

In [86]:
sales_df = sales_df.drop_duplicates()

In [87]:
print(sales_df.duplicated().sum())

0

In [93]:
print(sales_df.isna().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [104]:
sales_df = sales_df.rename(columns={
    "PassengerId": "Passenger_ID",
    "Pclass": "Passenger_Class",
    "SibSp": "Sibling_Spouse",
    "Parch": "Parent_Child"
})

In [105]:
sales_df["Name"] = (
    sales_df["Name"]
    .str.title()
    .str.strip()
)

In [106]:
sales_df["Sex"] = (
    sales_df["Sex"]
    .str.title()
    .str.strip()
)

In [107]:
sales_df["Embarked"] = (
    sales_df["Embarked"]
    .fillna("Unknown")
    .str.upper()
)

In [108]:
sales_df["Age"] = sales_df["Age"].fillna(
    sales_df["Age"].median()
)

In [109]:
sales_df["Fare"] = pd.to_numeric(
    sales_df["Fare"],
    errors="coerce"
)

In [110]:
Q1 = sales_df["Fare"].quantile(0.25)

In [111]:
Q3 = sales_df["Fare"].quantile(0.75)

In [112]:
IQR = Q3 - Q1

In [114]:
lower_bound = Q1 - 1.5 * IQR

upper_bound = Q3 + 1.5 * IQR

In [115]:
sales_df = sales_df[
    (sales_df["Fare"] >= lower_bound) &
    (sales_df["Fare"] <= upper_bound)
]

In [116]:
display(sales_df.head())

   Passenger_ID  Survived  Passenger_Class                                          Name     Sex   Age  Sibling_Spouse  Parent_Child            Ticket     Fare Cabin Embarked
0             1         0                3                       Braund, Mr. Owen Harris    Male  22.0               1             0         A/5 21171   7.2500   NaN        S
2             3         1                3                        Heikkinen, Miss. Laina  Female  26.0               0             0  STON/O2. 3101282   7.9250   NaN        S
3             4         1                1  Futrelle, Mrs. Jacques Heath (Lily May Peel)  Female  35.0               1             0            113803  53.1000  C123        S
4             5         0                3                      Allen, Mr. William Henry    Male  35.0               0             0            373450   8.0500   NaN        S
5             6         0                3                              Moran, Mr. James    Male  28.0               0             0            330877   8.4583   NaN        Q

In [117]:
print(sales_df.dtypes)

Passenger_ID         int64
Survived             int64
Passenger_Class      int64
Name                object
Sex                 object
Age                float64
Sibling_Spouse       int64
Parent_Child         int64
Ticket              object
Fare               float64
Cabin               object
Embarked            object
dtype: object

In [118]:
assert sales_df.duplicated().sum() == 0

In [119]:
print("Validation Successful!")

Validation Successful!

In [120]:
sales_df.to_csv("cleaned_retail_sales_dataset.csv", index=False)

In [121]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [122]:
# Spotify Streaming History

In [123]:
spotify_df = pd.read_csv("spotify_history.csv")

In [124]:
display(spotify_df.head())

        spotify_track_uri                   ts    platform  ms_played                                     track_name        artist_name                          album_name reason_start reason_end  shuffle  skipped
0  2J3n32GeLmMjwuAzyhcSNe  2013-07-08 02:44:34  web player       3185                            Say It, Just Say It       The Mowgli's                Waiting For The Dawn     autoplay   clickrow    False    False
1  1oHxIPqJyvAYHy0PVrDU98  2013-07-08 02:45:37  web player      61865  Drinking from the Bottle (feat. Tinie Tempah)      Calvin Harris                           18 Months     clickrow   clickrow    False    False
2  487OPlneJNni3NWC8SYqhW  2013-07-08 02:50:24  web player     285386                                    Born To Die       Lana Del Rey  Born To Die - The Paradise Edition     clickrow    unknown    False    False
3  5IyblF777jLZj1vGHG2UD3  2013-07-08 02:52:40  web player     134022                               Off To The Races       Lana Del Rey  Born To Die - The Paradise Edition    trackdone   clickrow    False    False
4  0GgAAB0ZMllFhbNc3mAodO  2013-07-08 03:17:52  web player          0                                      Half Mast  Empire Of The Sun                  Walking On A Dream     clickrow    nextbtn    False    False

In [125]:
print(spotify_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149860 entries, 0 to 149859
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   spotify_track_uri  149860 non-null  object
 1   ts                 149860 non-null  object
 2   platform           149860 non-null  object
 3   ms_played          149860 non-null  int64
 4   track_name         149860 non-null  object
 5   artist_name        149860 non-null  object
 6   album_name         149860 non-null  object
 7   reason_start       149717 non-null  object
 8   reason_end         149743 non-null  object
 9   shuffle            149860 non-null  bool
 10  skipped            149860 non-null  bool
dtypes: bool(2), int64(1), object(8)
memory usage: 10.6+ MB
None

In [126]:
print(spotify_df.shape)

(149860, 11)

In [127]:
print(spotify_df.duplicated().sum())

1185

In [128]:
spotify_df = spotify_df.drop_duplicates()

In [129]:
print(spotify_df.duplicated().sum())

0

In [130]:
print(spotify_df.isna().sum())

spotify_track_uri      0
ts                     0
platform               0
ms_played              0
track_name             0
artist_name            0
album_name             0
reason_start         143
reason_end           117
shuffle                0
skipped                0
dtype: int64

In [131]:
print(spotify_df.columns)

Index(['spotify_track_uri', 'ts', 'platform', 'ms_played', 'track_name', 'artist_name', 'album_name', 'reason_start', 'reason_end', 'shuffle', 'skipped'], dtype='object')

In [140]:
spotify_df["ts"] = pd.to_datetime(
    spotify_df["ts"],
    errors="coerce"
)

In [141]:
spotify_df["track_name"] = (
    spotify_df["track_name"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [142]:
spotify_df["artist_name"] = (
    spotify_df["artist_name"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [143]:
spotify_df["album_name"] = (
    spotify_df["album_name"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [144]:
spotify_df["spotify_track_uri"] = (
    spotify_df["spotify_track_uri"]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
)

In [145]:
display(spotify_df.head())

        spotify_track_uri                  ts    platform  ms_played                                     track_name        artist_name                          album_name reason_start reason_end  shuffle  skipped
0  2J3n32GeLmMjwuAzyhcSNe 2013-07-08 02:44:34  web player       3185                            Say It, Just Say It       The Mowgli'S                Waiting For The Dawn     autoplay   clickrow    False    False
1  1oHxIPqJyvAYHy0PVrDU98 2013-07-08 02:45:37  web player      61865  Drinking From The Bottle (Feat. Tinie Tempah)      Calvin Harris                           18 Months     clickrow   clickrow    False    False
2  487OPlneJNni3NWC8SYqhW 2013-07-08 02:50:24  web player     285386                                    Born To Die       Lana Del Rey  Born To Die - The Paradise Edition     clickrow    unknown    False    False
3  5IyblF777jLZj1vGHG2UD3 2013-07-08 02:52:40  web player     134022                               Off To The Races       Lana Del Rey  Born To Die - The Paradise Edition    trackdone   clickrow    False    False
4  0GgAAB0ZMllFhbNc3mAodO 2013-07-08 03:17:52  web player          0                                      Half Mast  Empire Of The Sun                  Walking On A Dream     clickrow    nextbtn    False    False

In [146]:
print(spotify_df.dtypes)

spotify_track_uri            object
ts                   datetime64[ns]
platform                     object
ms_played                     int64
track_name                   object
artist_name                  object
album_name                   object
reason_start                 object
reason_end                   object
shuffle                        bool
skipped                        bool
dtype: object

In [147]:
assert spotify_df.duplicated().sum() == 0

In [148]:
print("Validation Successful!")

Validation Successful!

In [149]:
spotify_df.to_csv(
    "cleaned_spotify_history_dataset.csv",
    index=False
)

In [150]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [151]:
# Data Science Job Postings

In [152]:
jobs_df = pd.read_csv("glassdoor job posting.csv")

In [153]:
display(jobs_df.head())

                                    Job Title  Salary Estimate                                    Job Description  Rating             Company Name Location                  Size  Founded  Type of ownership                               Industry                  Sector                     Revenue
0             Big Data & Analytics Consultant               -1  Are you passionate about analytics? Would you ...     3.9              Amazon\n3.9  Jakarta      10000+ Employees     1994   Company - Public                               Internet  Information Technology          $10+ billion (USD)
1               Data Scientist - QuantumBlack               -1  QUALIFICATIONS\nBachelor or Masters or PhD lev...     4.4  McKinsey & Company\n4.4  Jakarta      10000+ Employees     1926  Company - Private                             Consulting       Business Services    Unknown / Non-Applicable
2                  IT Security Data Scientist               -1  Job Title:\nIT Security Data Scientist\n\nJob ...     3.9     Nomura Holdings\n3.9     Emea      10000+ Employees     1925   Company - Public  Investment Banking & Asset Management                 Finance          $10+ billion (USD)
3  Data Scientist - Risk Modelling Specialist               -1  Company Description\n\nCermati is a financial ...     4.4         Cermati.com\n4.4  Jakarta     1 to 50 Employees       -1  Company - Private                               Internet  Information Technology  Less than $1 million (USD)
4                              Data Scientist               -1  HappyFresh is Southeast Asia's #1 Online Groce...     4.3          HappyFresh\n4.3  Jakarta  201 to 500 Employees     2014  Company - Private                               Internet  Information Technology    Unknown / Non-Applicable

In [154]:
print(jobs_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          150 non-null    object
 1   Salary Estimate    150 non-null    int64
 2   Job Description    150 non-null    object
 3   Rating             150 non-null    float64
 4   Company Name       150 non-null    object
 5   Location           150 non-null    object
 6   Size               150 non-null    object
 7   Founded            150 non-null    int64
 8   Type of ownership  150 non-null    object
 9   Industry           150 non-null    object
 10  Sector             150 non-null    object
 11  Revenue            150 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 14.2+ KB
None

In [155]:
print(jobs_df.shape)

(150, 12)

In [156]:
print(jobs_df.duplicated().sum())

7

In [157]:
jobs_df = jobs_df.drop_duplicates()

In [158]:
print(jobs_df.duplicated().sum())

0

In [159]:
print(jobs_df.isna().sum())

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
dtype: int64

In [160]:
jobs_df = jobs_df.rename(columns={
    "Job Title": "Job_Title",
    "Salary Estimate": "Salary_Estimate",
    "Job Description": "Job_Description",
    "Company Name": "Company_Name",
    "Type of ownership": "Ownership_Type"
})

In [161]:
print(jobs_df.columns)

Index(['Job_Title', 'Salary_Estimate', 'Job_Description', 'Rating', 'Company_Name', 'Location', 'Size', 'Founded', 'Ownership_Type', 'Industry', 'Sector', 'Revenue'], dtype='object')

In [162]:
jobs_df["Job_Title"] = (
    jobs_df["Job_Title"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [163]:
jobs_df["Company_Name"] = (
    jobs_df["Company_Name"]
    .fillna("Unknown")
    .astype(str)
    .str.replace(r"\n.*", "", regex=True)
    .str.strip()
)

In [164]:
jobs_df["Location"] = (
    jobs_df["Location"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [165]:
jobs_df["Industry"] = (
    jobs_df["Industry"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [166]:
jobs_df["Sector"] = (
    jobs_df["Sector"]
    .fillna("Unknown")
    .astype(str)
    .str.title()
    .str.strip()
)

In [167]:
jobs_df["Job_Description"] = (
    jobs_df["Job_Description"]
    .fillna("Not Available")
    .astype(str)
    .str.strip()
)

In [168]:
jobs_df["Salary_Estimate"] = pd.to_numeric(
    jobs_df["Salary_Estimate"],
    errors="coerce"
)

In [169]:
Q1 = jobs_df["Salary_Estimate"].quantile(0.25)

Q3 = jobs_df["Salary_Estimate"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR

upper_bound = Q3 + 1.5 * IQR

In [170]:
jobs_df = jobs_df[
    (jobs_df["Salary_Estimate"] >= lower_bound) &
    (jobs_df["Salary_Estimate"] <= upper_bound)
]

In [171]:
display(jobs_df.head())

                                    Job_Title  Salary_Estimate                                    Job_Description  Rating        Company_Name Location                  Size  Founded     Ownership_Type                               Industry                  Sector                     Revenue
0             Big Data & Analytics Consultant               -1  Are you passionate about analytics? Would you ...     3.9              Amazon  Jakarta      10000+ Employees     1994   Company - Public                               Internet  Information Technology          $10+ billion (USD)
1               Data Scientist - Quantumblack               -1  QUALIFICATIONS\nBachelor or Masters or PhD lev...     4.4  McKinsey & Company  Jakarta      10000+ Employees     1926  Company - Private                             Consulting       Business Services    Unknown / Non-Applicable
2                  It Security Data Scientist               -1  Job Title:\nIT Security Data Scientist\n\nJob ...     3.9     Nomura Holdings     Emea      10000+ Employees     1925   Company - Public  Investment Banking & Asset Management                 Finance          $10+ billion (USD)
3  Data Scientist - Risk Modelling Specialist               -1  Company Description\n\nCermati is a financial ...     4.4         Cermati.com  Jakarta     1 to 50 Employees       -1  Company - Private                               Internet  Information Technology  Less than $1 million (USD)
4                              Data Scientist               -1  HappyFresh is Southeast Asia's #1 Online Groce...     4.3          HappyFresh  Jakarta  201 to 500 Employees     2014  Company - Private                               Internet  Information Technology    Unknown / Non-Applicable

In [172]:
print(jobs_df.dtypes)

Job_Title           object
Salary_Estimate      int64
Job_Description     object
Rating             float64
Company_Name        object
Location            object
Size                object
Founded              int64
Ownership_Type      object
Industry            object
Sector              object
Revenue             object
dtype: object

In [173]:
assert jobs_df.duplicated().sum() == 0

In [174]:
print("Validation Successful!")

Validation Successful!

In [175]:
jobs_df.to_csv(
    "cleaned_data_science_jobs_dataset.csv",
    index=False
)

In [176]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [1]:
# NYC Taxi Trips Dataset

In [5]:
import pandas as pd

In [6]:
taxi_df = pd.read_csv("data.csv")

In [7]:
taxi_df = pd.read_csv("data.csv")

In [8]:
display(taxi_df.head())

,Unnamed: 0,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,imp_surcharge,total_amount
0,0,2,2015-07-18 11:25:58,2015-07-18 11:43:47,1,7.21,-73.862762,40.769028,1.0,N,-73.949203,40.722584,1,22.5,0.0,0.5,4.66,0.00,0.3,27.96
1,1,1,2015-03-15 12:50:01,2015-03-15 13:23:35,1,10.80,-73.870926,40.773727,NaN,N,-73.988228,40.765694,1,34.5,0.0,0.5,8.10,5.33,0.3,48.73
2,2,2,2015-04-30 12:25:44,2015-04-30 13:03:51,1,4.28,-73.978180,40.762341,NaN,N,-74.008911,40.710789,1,24.5,0.0,0.5,2.50,0.00,0.3,27.80
3,3,2,2015-05-28 08:47:56,2015-05-28 09:26:08,1,18.47,-73.776711,40.645302,NaN,N,-73.843422,40.852852,1,51.0,0.0,0.5,7.00,5.54,0.3,64.34
4,4,1,2015-06-20 19:36:17,2015-06-20 20:10:49,1,15.50,-73.777054,40.644947,NaN,Y,-73.946800,40.725021,1,44.5,0.0,0.5,9.06,0.00,0.3,54.36

In [9]:
print(taxi_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          200000 non-null  int64
 1   vendor_id           200000 non-null  int64
 2   pickup_datetime     200000 non-null  object
 3   dropoff_datetime    200000 non-null  object
 4   passenger_count     200000 non-null  int64
 5   trip_distance       200000 non-null  float64
 6   pickup_longitude    151528 non-null  float64
 7   pickup_latitude     151528 non-null  float64
 8   rate_code           148838 non-null  float64
 9   store_and_fwd_flag  200000 non-null  object
 10  dropoff_longitude   151528 non-null  float64
 11  dropoff_latitude    151528 non-null  float64
 12  payment_type        200000 non-null  int64
 13  fare_amount         200000 non-null  float64
 14  extra               200000 non-null  float64
 15  mta_tax             200000 non-null  float64
 16  tip_amount          200000 non-null  float64
 17  tolls_amount        200000 non-null  float64
 18  imp_surcharge       200000 non-null  float64
 19  total_amount        200000 non-null  float64
dtypes: float64(13), int64(4), object(3)
memory usage: 30.5+ MB
None

In [10]:
print(taxi_df.shape)

(200000, 20)

In [11]:
print(taxi_df.duplicated().sum())

0

In [12]:
taxi_df = taxi_df.drop_duplicates()

In [13]:
print(taxi_df.duplicated().sum())

0

In [14]:
print(taxi_df.isna().sum())

Unnamed: 0                0
vendor_id                 0
pickup_datetime           0
dropoff_datetime          0
passenger_count           0
trip_distance             0
pickup_longitude      48472
pickup_latitude       48472
rate_code             51162
store_and_fwd_flag        0
dropoff_longitude     48472
dropoff_latitude      48472
payment_type              0
fare_amount               0
extra                     0
mta_tax                   0
tip_amount                0
tolls_amount              0
imp_surcharge             0
total_amount              0
dtype: int64

In [15]:
print(taxi_df.columns)

Index(['Unnamed: 0', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'rate_code', 'store_and_fwd_flag',
       'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'imp_surcharge',
       'total_amount'],
      dtype='object')

In [16]:
taxi_df = taxi_df.rename(columns={
    "passenger_count": "Passenger_Count",
    "trip_distance": "Trip_Distance",
    "fare_amount": "Fare_Amount",
    "pickup_longitude": "Pickup_Longitude",
    "pickup_latitude": "Pickup_Latitude",
    "dropoff_longitude": "Dropoff_Longitude",
    "dropoff_latitude": "Dropoff_Latitude"
})

In [17]:
taxi_df["Passenger_Count"] = pd.to_numeric(
    taxi_df["Passenger_Count"],
    errors="coerce"
)

In [18]:
taxi_df["Fare_Amount"] = pd.to_numeric(
    taxi_df["Fare_Amount"],
    errors="coerce"
)

In [19]:
taxi_df["Trip_Distance"] = pd.to_numeric(
    taxi_df["Trip_Distance"],
    errors="coerce"
)

In [20]:
taxi_df["Passenger_Count"] = taxi_df["Passenger_Count"].fillna(
    taxi_df["Passenger_Count"].median()
)

In [21]:
taxi_df = taxi_df[
    (taxi_df["Pickup_Latitude"].between(-90, 90)) &
    (taxi_df["Dropoff_Latitude"].between(-90, 90)) &
    (taxi_df["Pickup_Longitude"].between(-180, 180)) &
    (taxi_df["Dropoff_Longitude"].between(-180, 180))
]

In [22]:
Q1 = taxi_df["Fare_Amount"].quantile(0.25)
Q3 = taxi_df["Fare_Amount"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [23]:
taxi_df = taxi_df[
    (taxi_df["Fare_Amount"] >= lower_bound) &
    (taxi_df["Fare_Amount"] <= upper_bound)
]

In [24]:
display(taxi_df.head())

,Unnamed: 0,vendor_id,pickup_datetime,dropoff_datetime,Passenger_Count,Trip_Distance,Pickup_Longitude,Pickup_Latitude,rate_code,store_and_fwd_flag,Dropoff_Longitude,Dropoff_Latitude,payment_type,Fare_Amount,extra,mta_tax,tip_amount,tolls_amount,imp_surcharge,total_amount
0,0,2,2015-07-18 11:25:58,2015-07-18 11:43:47,1,7.21,-73.862762,40.769028,1.0,N,-73.949203,40.722584,1,22.5,0.0,0.5,4.66,0.00,0.3,27.96
1,1,1,2015-03-15 12:50:01,2015-03-15 13:23:35,1,10.80,-73.870926,40.773727,NaN,N,-73.988228,40.765694,1,34.5,0.0,0.5,8.10,5.33,0.3,48.73
2,2,2,2015-04-30 12:25:44,2015-04-30 13:03:51,1,4.28,-73.978180,40.762341,NaN,N,-74.008911,40.710789,1,24.5,0.0,0.5,2.50,0.00,0.3,27.80
3,3,2,2015-05-28 08:47:56,2015-05-28 09:26:08,1,18.47,-73.776711,40.645302,NaN,N,-73.843422,40.852852,1,51.0,0.0,0.5,7.00,5.54,0.3,64.34
4,4,1,2015-06-20 19:36:17,2015-06-20 20:10:49,1,15.50,-73.777054,40.644947,NaN,Y,-73.946800,40.725021,1,44.5,0.0,0.5,9.06,0.00,0.3,54.36

In [25]:
print(taxi_df.dtypes)

Unnamed: 0              int64
vendor_id               int64
pickup_datetime        object
dropoff_datetime       object
Passenger_Count         int64
Trip_Distance         float64
Pickup_Longitude      float64
Pickup_Latitude       float64
rate_code             float64
store_and_fwd_flag     object
Dropoff_Longitude     float64
Dropoff_Latitude      float64
payment_type            int64
Fare_Amount           float64
extra                 float64
mta_tax               float64
tip_amount            float64
tolls_amount          float64
imp_surcharge         float64
total_amount          float64
dtype: object

In [26]:
assert taxi_df.duplicated().sum() == 0

In [27]:
print("Validation Successful!")

Validation Successful!

In [28]:
taxi_df.to_csv(
    "cleaned_nyc_taxi_dataset.csv",
    index=False
)

In [29]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!